# Generated by Django 6.0 on 2026-09-04 10:57

import bench.control_plane.api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=bench.control_plane.api.models.agent_id,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("management", "Management"), ("worker", "Worker")],
                        max_length=16,
                    ),
                ),
                ("role", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("dismissed", "Dismissed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("capability", models.CharField(blank=True, max_length=16, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.BigIntegerField(unique=True)),
                ("event_id", models.CharField(max_length=64)),
                ("ts", models.CharField(max_length=40)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                ("actor", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("dispatch_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "worker_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("machine_id", models.CharField(blank=True, max_length=512, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charge_id", models.CharField(max_length=64, unique=True)),
                ("ts", models.CharField(max_length=40)),
                ("task_id", models.CharField(db_index=True, max_length=64)),
                ("category", models.CharField(max_length=24)),
                ("amount_usd", models.FloatField()),
                ("worker_id", models.CharField(blank=True, max_length=64, null=True)),
                ("machine_id", models.CharField(blank=True, max_length=512, null=True)),
                ("unit", models.CharField(blank=True, max_length=24, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("over_budget", models.BooleanField(default=False)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=bench.control_plane.api.models.goal_id,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("planning", "Planning"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "name",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("match", models.JSONField()),
                ("effect", models.CharField(max_length=12)),
                ("reason", models.TextField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=bench.control_plane.api.models.task_id,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("sandbox", "Sandbox"),
                            ("browser", "Browser"),
                            ("desktop", "Desktop"),
                        ],
                        max_length=16,
                    ),
                ),
                ("instructions", models.TextField(blank=True, default="")),
                ("success_criteria", models.JSONField(default=list)),
                ("depends_on", models.JSONField(default=list)),
                ("tool", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("dispatching", "Dispatching"),
                            ("denied", "Denied"),
                            ("escalated", "Escalated"),
                            ("running", "Running"),
                            ("quarantine", "Quarantine"),
                            ("review", "Review"),
                            ("done", "Done"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("result", models.JSONField(blank=True, null=True)),
                ("review", models.JSONField(blank=True, null=True)),
                ("quarantine", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="api.goal",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="api.task",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.CharField(max_length=512, primary_key=True, serialize=False),
                ),
                ("kind", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booting", "Booting"),
                            ("ready", "Ready"),
                            ("destroyed", "Destroyed"),
                            ("failed", "Failed"),
                        ],
                        default="booting",
                        max_length=16,
                    ),
                ),
                ("preview_urls", models.JSONField(default=dict)),
                (
                    "stream_url",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "recording_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("launched_at", models.DateTimeField(auto_now_add=True)),
                ("destroyed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machines",
                        to="api.agent",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machines",
                        to="api.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-launched_at"],
            },
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=bench.control_plane.api.models.escalation_id,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="api.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=bench.control_plane.api.models.dispatch_id,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("capability", models.CharField(max_length=16)),
                ("payload", models.JSONField(default=dict)),
                ("effect", models.CharField(max_length=12)),
                ("audit", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True, default="")),
                ("matched_rules", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="api.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="api.task",
            ),
        ),
    ]
