"""Where orchestration steps go besides the audit log.

The orchestrator always writes to ``bench.audit``. A sink is the *extra*
persistence hook — the control plane implements one that updates its Task /
Agent / Machine / Dispatch rows; standalone runs use :class:`NullSink`.
"""

from __future__ import annotations

from typing import Any, Protocol

from bench.agents.models import Plan, Review, TaskSpec, WorkerResult


class OrchestrationSink(Protocol):
    def on_plan(self, plan: Plan) -> None: ...
    def on_task_status(self, spec: TaskSpec, status: str, *, detail: str = "") -> None: ...
    def on_dispatch(self, spec: TaskSpec, decision: Any) -> None: ...
    def on_worker_hired(self, spec: TaskSpec, worker_id: str) -> None: ...
    def on_machine(self, spec: TaskSpec, worker_id: str, handle: Any) -> None: ...
    def on_worker_result(self, spec: TaskSpec, worker_id: str, result: WorkerResult) -> None: ...
    def on_quarantine(self, spec: TaskSpec, result: Any) -> None: ...
    def on_review(self, spec: TaskSpec, review: Review) -> None: ...
    def on_escalation(self, spec: TaskSpec, reason: str) -> None: ...


class NullSink:
    def on_plan(self, plan: Plan) -> None: ...
    def on_task_status(self, spec: TaskSpec, status: str, *, detail: str = "") -> None: ...
    def on_dispatch(self, spec: TaskSpec, decision: Any) -> None: ...
    def on_worker_hired(self, spec: TaskSpec, worker_id: str) -> None: ...
    def on_machine(self, spec: TaskSpec, worker_id: str, handle: Any) -> None: ...
    def on_worker_result(self, spec: TaskSpec, worker_id: str, result: WorkerResult) -> None: ...
    def on_quarantine(self, spec: TaskSpec, result: Any) -> None: ...
    def on_review(self, spec: TaskSpec, review: Review) -> None: ...
    def on_escalation(self, spec: TaskSpec, reason: str) -> None: ...


__all__ = ["OrchestrationSink", "NullSink"]
